//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIVENDAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportadora
    {
        public int Id { get; set; }
        public string Cnpj { get; set; }
        public string Senha { get; set; }
        public int Tipo { get; set; }
    }
}
